/**
 * Al Shaheed Trading and Equipment Co.
 * Master Constants, Commodities, Global Ports, Incoterms & Demo Data Seed
 */

import { ScrapListing, BuyerRequirement, User, Transaction, AgentAssignment, TradeDocument, Notification, AuditLog, SystemSettings } from '../types';

export const COMPANY_INFO = {
  name: 'AL SHAHEED TRADING AND EQUIPMENT CO',
  shortName: 'Al Shaheed Recycling',
  tagline: 'Global Scrap Trading. Smarter Supply. Reliable Demand.',
  website: 'www.alshaheedrecycling.com',
  websiteUrl: 'https://www.alshaheedrecycling.com',
  email: 'alshaheedrecycling@gmail.com',
  phone1: '+974 30437712',
  phone2: '+974 30437733',
  address: 'Building 45, Street 810, Industrial Area, Zone 57, Doha, State of Qatar',
  country: 'Qatar',
  city: 'Doha',
};

export const COMMODITY_CATEGORIES = [
  'Metal Scrap',
  'Paper Waste',
  'Industrial Recyclables & Equipment',
  'Plastic Recyclables',
  'Machinery & Heavy Equipment',
];

export const COMMODITY_CATEGORIES_DATA = [
  {
    id: 'metal-scrap',
    name: 'Metal Scrap',
    description: 'Ferrous & non-ferrous industrial metals, shredded steel, copper cathodes, and aluminum scrap.',
    subcategories: [
      'HMS 1&2 (80:20 / 90:10)',
      'HMS 1 (Heavy Melting Scrap 1)',
      'HMS 2 (Heavy Melting Scrap 2)',
      'Shredded Steel Scrap 211',
      'Cast Iron Scrap',
      'Stainless Steel 304 / 316',
      'Copper Cathode / Birch / Cliff',
      'Aluminium Tense / Tabor / Extrusion 6063',
      'Brass Scrap (Honey / Ocean)',
      'Zinc Scrap',
      'Mixed Metal Scrap (Zorba / Zurik)',
    ],
  },
  {
    id: 'paper-waste',
    name: 'Paper Waste',
    description: 'Baled recyclable paper, OCC cardboard, ONP, and clean bleached pulp grades.',
    subcategories: [
      'OCC (Old Corrugated Cardboard - Grade 11 / 12)',
      'ONP (Old Newspapers)',
      'Mixed Paper Scrap',
      'White Office Paper (Sorted Office Paper - SOP)',
      'Hard White Shavings (HWS)',
      'Magazine Scrap (OMG)',
      'Kraft Paper & Multiwall Bag Waste',
      'Pulp & Paper Mill Broke',
    ],
  },
  {
    id: 'industrial-recyclables',
    name: 'Industrial Recyclables & Equipment',
    description: 'Industrial scrap, HDPE/PET baled plastics, tires, and retired decommissioning machinery.',
    subcategories: [
      'HDPE Regrind & Bales (Blow & Injection)',
      'PET Flakes & Bales',
      'LDPE Film Scrap 98/2',
      'Decommissioned Plant Equipment & Machinery',
      'Used Rails (R50 / R65)',
    ],
  },
];

export const INCOTERMS = ['CFR', 'CIF', 'FOB', 'EXW', 'FCA', 'CIP', 'DAP'];
export const INCOTERMS_OPTIONS = INCOTERMS;

export const PORTS_OF_SHIPPING = [
  'Hamad Port (Doha)',
  'Ras Laffan Port',
  'Jebel Ali Port (Dubai)',
  'Khalifa Port (Abu Dhabi)',
  'King Abdulaziz Port (Dammam)',
  'Port of Rotterdam',
  'Port of Antwerp',
  'Port of Houston',
];

export const DESTINATION_PORTS = [
  'Nhava Sheva (JNPT Mumbai)',
  'Mundra Port (Gujarat)',
  'Chennai Port',
  'Chittagong (Chattogram) Port',
  'Port Qasim (Karachi)',
  'Aliaga Port (Izmir)',
  'Iskenderun Port',
  'Hai Phong Port',
  'Ho Chi Minh Port (Cat Lai)',
  'Alexandria Port',
];

export const GLOBAL_PORTS = [
  { country: 'Qatar', port: 'Hamad Port (Doha)' },
  { country: 'Qatar', port: 'Ras Laffan Port' },
  { country: 'United Arab Emirates', port: 'Jebel Ali Port (Dubai)' },
  { country: 'United Arab Emirates', port: 'Khalifa Port (Abu Dhabi)' },
  { country: 'Saudi Arabia', port: 'King Abdulaziz Port (Dammam)' },
  { country: 'Saudi Arabia', port: 'Jeddah Islamic Port' },
  { country: 'India', port: 'Nhava Sheva (JNPT Mumbai)' },
  { country: 'India', port: 'Mundra Port (Gujarat)' },
  { country: 'India', port: 'Chennai Port' },
  { country: 'Bangladesh', port: 'Chittagong (Chattogram) Port' },
  { country: 'Pakistan', port: 'Port Qasim (Karachi)' },
  { country: 'Turkey', port: 'Aliaga Port (Izmir)' },
  { country: 'Turkey', port: 'Iskenderun Port' },
  { country: 'Vietnam', port: 'Hai Phong Port' },
  { country: 'Vietnam', port: 'Ho Chi Minh Port (Cat Lai)' },
  { country: 'Egypt', port: 'Alexandria Port' },
  { country: 'Netherlands', port: 'Port of Rotterdam' },
  { country: 'Germany', port: 'Port of Hamburg' },
  { country: 'Belgium', port: 'Port of Antwerp' },
  { country: 'United States', port: 'Port of Houston' },
  { country: 'United States', port: 'Port of Los Angeles' },
  { country: 'China', port: 'Ningbo-Zhoushan Port' },
  { country: 'China', port: 'Shanghai Port' },
];

export const COUNTRIES_LIST = [
  'Qatar', 'United Arab Emirates', 'Saudi Arabia', 'Oman', 'Kuwait', 'Bahrain',
  'India', 'Bangladesh', 'Pakistan', 'Turkey', 'Egypt', 'Vietnam', 'Indonesia',
  'Malaysia', 'Thailand', 'South Korea', 'Japan', 'China', 'Germany', 'Netherlands',
  'Belgium', 'United Kingdom', 'United States', 'Canada', 'South Africa',
];

export const PAYMENT_TERMS_OPTIONS = [
  '100% LC at Sight (Irrevocable & Confirmed)',
  '30% TT Advance + 70% against BL copy',
  '20% TT Advance + 80% LC at Sight',
  'Cash Against Documents (CAD)',
  '100% Advance Wire Transfer',
];

export const PACKAGING_OPTIONS = [
  'Loose in 20ft Dry Cargo Container (Approx 25-28 MT)',
  'Hydraulically Compressed Bales (Avg 500-800 kg/bale)',
  'Bundles strapped with high-tensile steel wire',
  'Bulk Vessel Load (3,000 - 15,000 MT charter)',
  'Big Bags (Jumbo Bags 1.0 - 1.5 MT)',
];

export const DEFAULT_SYSTEM_SETTINGS: SystemSettings = {
  companyName: COMPANY_INFO.name,
  logoUrl: '/logo.svg',
  website: COMPANY_INFO.website,
  email: COMPANY_INFO.email,
  phone1: COMPANY_INFO.phone1,
  phone2: COMPANY_INFO.phone2,
  address: COMPANY_INFO.address,
  defaultAgentRatePerTon: 15, // $15 / MT default
  tradingCurrencies: ['USD', 'QAR', 'EUR', 'AED', 'SAR', 'INR', 'GBP', 'CNY'],
  primaryCurrency: 'USD',
  minMatchScoreThreshold: 65,
  autoMatchNotification: true,
};

// Initial Demo Users
export const INITIAL_USERS: User[] = [
  {
    id: 'usr-admin-01',
    email: 'admin@alshaheedrecycling.com',
    name: 'admin',
    role: 'ADMIN',
    companyName: 'Al Shaheed Trading and Equipment Co',
    phone: '+974 30437712',
    country: 'Qatar',
    city: 'Doha',
    status: 'ACTIVE',
    createdAt: '2026-01-10T08:00:00Z',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
  },
  // 5 Suppliers
  {
    id: 'usr-sup-01',
    email: 'supplier.gulfmetal@example.com',
    name: 'Tariq Al-Mansoor',
    role: 'SUPPLIER',
    companyName: 'Gulf Heavy Smelting & Metal Recovery Ltd',
    phone: '+974 44558899',
    country: 'Qatar',
    city: 'Doha',
    businessRegNumber: 'CR-QA-882910',
    taxVatNumber: 'TIN-994821',
    commodityCategories: ['Metal Scrap'],
    status: 'ACTIVE',
    createdAt: '2026-02-01T09:30:00Z',
  },
  {
    id: 'usr-sup-02',
    email: 'supplier.doharecycling@example.com',
    name: 'Ahmed Bin Salem',
    role: 'SUPPLIER',
    companyName: 'Doha Paper Mills & Pulp Recycling Est',
    phone: '+974 55112233',
    country: 'Qatar',
    city: 'Al Wakrah',
    businessRegNumber: 'CR-QA-109283',
    taxVatNumber: 'TIN-401928',
    commodityCategories: ['Paper Waste'],
    status: 'ACTIVE',
    createdAt: '2026-02-05T11:00:00Z',
  },
  {
    id: 'usr-sup-03',
    email: 'supplier.emiratesiron@example.com',
    name: 'Rashid Khan',
    role: 'SUPPLIER',
    companyName: 'Emirates Industrial Ferrous Logistics FZE',
    phone: '+971 4 8812345',
    country: 'United Arab Emirates',
    city: 'Dubai',
    businessRegNumber: 'FZE-DXB-9831',
    commodityCategories: ['Metal Scrap'],
    status: 'ACTIVE',
    createdAt: '2026-02-12T14:15:00Z',
  },
  {
    id: 'usr-sup-04',
    email: 'supplier.saudiecocorp@example.com',
    name: 'Fahad Al-Otaibi',
    role: 'SUPPLIER',
    companyName: 'Saudi Eco Material Processing Co',
    phone: '+966 13 8920192',
    country: 'Saudi Arabia',
    city: 'Dammam',
    businessRegNumber: 'CR-SA-205019',
    commodityCategories: ['Paper Waste', 'Metal Scrap'],
    status: 'ACTIVE',
    createdAt: '2026-02-18T10:00:00Z',
  },
  {
    id: 'usr-sup-05',
    email: 'supplier.rotterdammetals@example.com',
    name: 'Jan De Vries',
    role: 'SUPPLIER',
    companyName: 'North Sea Non-Ferrous & Alloy BV',
    phone: '+31 10 4928172',
    country: 'Netherlands',
    city: 'Rotterdam',
    businessRegNumber: 'KVK-8827192',
    commodityCategories: ['Metal Scrap'],
    status: 'ACTIVE',
    createdAt: '2026-02-22T13:40:00Z',
  },

  // 5 Buyers
  {
    id: 'usr-buy-01',
    email: 'buyer.tatafoundry@example.com',
    name: 'Rajesh Sharma',
    role: 'BUYER',
    companyName: 'Bharat Steelworks & Foundries Ltd',
    phone: '+91 22 66778899',
    country: 'India',
    city: 'Mumbai',
    businessRegNumber: 'CIN-U27100MH1998',
    typicalVolume: '3,000 MT / Month',
    commodityCategories: ['Metal Scrap'],
    status: 'ACTIVE',
    createdAt: '2026-02-03T10:20:00Z',
  },
  {
    id: 'usr-buy-02',
    email: 'buyer.bengalpaper@example.com',
    name: 'Kamrul Hassan',
    role: 'BUYER',
    companyName: 'Chattogram Packaging & Kraft Mills Ltd',
    phone: '+880 31 718291',
    country: 'Bangladesh',
    city: 'Chittagong',
    businessRegNumber: 'RJSC-CTG-4821',
    typicalVolume: '1,500 MT / Month',
    commodityCategories: ['Paper Waste'],
    status: 'ACTIVE',
    createdAt: '2026-02-08T15:00:00Z',
  },
  {
    id: 'usr-buy-03',
    email: 'buyer.anadolusteel@example.com',
    name: 'Mustafa Demir',
    role: 'BUYER',
    companyName: 'Anadolu EAF Steelmaking & Rolling AS',
    phone: '+90 232 4419281',
    country: 'Turkey',
    city: 'Izmir',
    businessRegNumber: 'MERSIS-0192837',
    typicalVolume: '5,000 MT / Month',
    commodityCategories: ['Metal Scrap'],
    status: 'ACTIVE',
    createdAt: '2026-02-14T09:10:00Z',
  },
  {
    id: 'usr-buy-04',
    email: 'buyer.saigonboard@example.com',
    name: 'Nguyen Van Minh',
    role: 'BUYER',
    companyName: 'Saigon Containerboard & Duplex Packaging Corp',
    phone: '+84 28 3829102',
    country: 'Vietnam',
    city: 'Ho Chi Minh City',
    typicalVolume: '2,000 MT / Month',
    commodityCategories: ['Paper Waste'],
    status: 'ACTIVE',
    createdAt: '2026-02-20T12:00:00Z',
  },
  {
    id: 'usr-buy-05',
    email: 'buyer.cairocopper@example.com',
    name: 'Ibrahim Mostafa',
    role: 'BUYER',
    companyName: 'Nile Cables & Non-Ferrous Smelting SAE',
    phone: '+20 2 2481928',
    country: 'Egypt',
    city: 'Cairo',
    typicalVolume: '800 MT / Month',
    commodityCategories: ['Metal Scrap'],
    status: 'ACTIVE',
    createdAt: '2026-02-25T11:45:00Z',
  },

  // 3 Agents
  {
    id: 'usr-agt-01',
    email: 'agent.khalid@example.com',
    name: 'Khalid Mansoor',
    role: 'AGENT',
    companyName: 'GCC Scrap Trade Brokerage',
    phone: '+974 66991122',
    country: 'Qatar',
    city: 'Doha',
    tradingRegion: 'Middle East & Indian Subcontinent',
    languages: ['Arabic', 'English', 'Hindi'],
    experienceYears: 12,
    status: 'ACTIVE',
    createdAt: '2026-02-02T08:00:00Z',
  },
  {
    id: 'usr-agt-02',
    email: 'agent.sanjay@example.com',
    name: 'Sanjay Patel',
    role: 'AGENT',
    companyName: 'South Asia Commodity Advisors',
    phone: '+91 98201 54321',
    country: 'India',
    city: 'Ahmedabad',
    tradingRegion: 'India, Bangladesh, SE Asia',
    languages: ['English', 'Gujarati', 'Hindi'],
    experienceYears: 15,
    status: 'ACTIVE',
    createdAt: '2026-02-06T14:30:00Z',
  },
  {
    id: 'usr-agt-03',
    email: 'agent.selim@example.com',
    name: 'Selim Erdogan',
    role: 'AGENT',
    companyName: 'Levant & Med Trade Partners',
    phone: '+90 532 8899001',
    country: 'Turkey',
    city: 'Istanbul',
    tradingRegion: 'Turkey, MENA & Southern Europe',
    languages: ['Turkish', 'English', 'Arabic'],
    experienceYears: 9,
    status: 'ACTIVE',
    createdAt: '2026-02-15T16:00:00Z',
  },
];

// 15 Realistic Scrap Material Listings
export const INITIAL_LISTINGS: ScrapListing[] = [
  {
    id: 'lst-101',
    supplierId: 'usr-sup-01',
    supplierCompanyName: 'Gulf Heavy Smelting & Metal Recovery Ltd',
    supplierContactName: 'Tariq Al-Mansoor',
    supplierEmail: 'supplier.gulfmetal@example.com',
    supplierPhone: '+974 44558899',
    supplierCountry: 'Qatar',
    commodityCategory: 'Metal Scrap',
    materialName: 'HMS 1&2 (80:20) Heavy Melting Steel Scrap',
    scrapType: 'Ferrous Metal',
    grade: 'ISRI 200-206 (Thickness >= 6mm)',
    description: 'Clean industrial heavy melting steel scrap sourced from decommissioned structural frameworks and pipeline cutting. Free from excessive rust, oil, mud, and non-metallic inclusions. Radioactivity tested & certified clean.',
    quantity: 1500,
    quantityUnit: 'MT',
    numberOfContainers: 58,
    pricePerUnit: 395,
    currency: 'USD',
    countryOfOrigin: 'Qatar',
    loadingLocation: 'Mesaieed Industrial City Scrap Yard',
    portOfShipping: 'Hamad Port (Doha)',
    destinationPort: 'Nhava Sheva (JNPT Mumbai)',
    packaging: 'Loose in 20ft Dry Cargo Container (Approx 25-28 MT)',
    qualitySpecification: 'Max 0.5% Impurities, Yield >92% after melting',
    inspectionAvailable: true,
    minOrderQuantity: 250,
    availabilityDate: '2026-08-25',
    validUntil: '2026-09-30',
    paymentTerms: '100% LC at Sight (Irrevocable & Confirmed)',
    incoterms: 'CFR',
    photos: [
      'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1532601224476-15c79f2f7a51?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1504917599217-d4dc5ebe6122?auto=format&fit=crop&w=800&q=80',
    ],
    status: 'AVAILABLE',
    adminPublishedPrice: true,
    assignedAgentId: 'usr-agt-01',
    assignedAgentName: 'Khalid Mansoor',
    agentRatePerTon: 18,
    interestedBuyerCount: 3,
    matchedDemandCount: 2,
    createdAt: '2026-08-15T09:00:00Z',
    updatedAt: '2026-08-19T14:20:00Z',
  },
  {
    id: 'lst-102',
    supplierId: 'usr-sup-02',
    supplierCompanyName: 'Doha Paper Mills & Pulp Recycling Est',
    supplierContactName: 'Ahmed Bin Salem',
    supplierEmail: 'supplier.doharecycling@example.com',
    supplierPhone: '+974 55112233',
    supplierCountry: 'Qatar',
    commodityCategory: 'Paper Waste',
    materialName: 'OCC Grade 11 (Old Corrugated Cardboard Bales)',
    scrapType: 'Corrugated Cardboard',
    grade: 'OCC 11 / ISRI PS-2022',
    description: 'High burst factor double and single wall corrugated container waste collected from commercial supermarkets and logistics centers. Moisture level strictly below 11%. No prohibitive materials.',
    quantity: 850,
    quantityUnit: 'MT',
    numberOfContainers: 38,
    pricePerUnit: 185,
    currency: 'USD',
    countryOfOrigin: 'Qatar',
    loadingLocation: 'Al Wakrah Industrial Logistics Park',
    portOfShipping: 'Hamad Port (Doha)',
    destinationPort: 'Chittagong (Chattogram) Port',
    packaging: 'Hydraulically Compressed Bales (Avg 500-800 kg/bale)',
    qualitySpecification: 'Outthrows <2%, Prohibitives <0.5%, Moisture <11%',
    inspectionAvailable: true,
    minOrderQuantity: 100,
    availabilityDate: '2026-08-22',
    validUntil: '2026-09-20',
    paymentTerms: '30% TT Advance + 70% against BL copy',
    incoterms: 'CIF',
    photos: [
      'https://images.unsplash.com/photo-1605600659908-0ef719419d41?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1530587191325-3db32d826c18?auto=format&fit=crop&w=800&q=80',
    ],
    status: 'AVAILABLE',
    adminPublishedPrice: true,
    assignedAgentId: 'usr-agt-02',
    assignedAgentName: 'Sanjay Patel',
    agentRatePerTon: 12,
    interestedBuyerCount: 2,
    matchedDemandCount: 1,
    createdAt: '2026-08-16T11:30:00Z',
    updatedAt: '2026-08-18T10:15:00Z',
  },
  {
    id: 'lst-103',
    supplierId: 'usr-sup-03',
    supplierCompanyName: 'Emirates Industrial Ferrous Logistics FZE',
    supplierContactName: 'Rashid Khan',
    supplierEmail: 'supplier.emiratesiron@example.com',
    supplierPhone: '+971 4 8812345',
    supplierCountry: 'United Arab Emirates',
    commodityCategory: 'Metal Scrap',
    materialName: 'Shredded Steel Scrap 211',
    scrapType: 'Ferrous Metal',
    grade: 'ISRI 211 (Density > 70 lbs/cu ft)',
    description: 'Magnetically separated homogeneous shredded steel scrap from automotive and light structural stamping. Free from non-ferrous, combustibles, and mud. Ready for rapid electric arc furnace charging.',
    quantity: 2200,
    quantityUnit: 'MT',
    numberOfContainers: 88,
    pricePerUnit: 415,
    currency: 'USD',
    countryOfOrigin: 'United Arab Emirates',
    loadingLocation: 'Jebel Ali Free Zone Scrap Terminal',
    portOfShipping: 'Jebel Ali Port (Dubai)',
    destinationPort: 'Aliaga Port (Izmir)',
    packaging: 'Loose in 20ft Dry Cargo Container (Approx 25-28 MT)',
    qualitySpecification: 'Metallic recovery >= 94%, S <0.03%, P <0.03%',
    inspectionAvailable: true,
    minOrderQuantity: 500,
    availabilityDate: '2026-08-28',
    validUntil: '2026-10-05',
    paymentTerms: '100% LC at Sight (Irrevocable & Confirmed)',
    incoterms: 'CFR',
    photos: [
      'https://images.unsplash.com/photo-1504917599217-d4dc5ebe6122?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=800&q=80',
    ],
    status: 'AVAILABLE',
    adminPublishedPrice: true,
    assignedAgentId: 'usr-agt-03',
    assignedAgentName: 'Selim Erdogan',
    agentRatePerTon: 20,
    interestedBuyerCount: 4,
    matchedDemandCount: 2,
    createdAt: '2026-08-14T08:15:00Z',
    updatedAt: '2026-08-19T16:00:00Z',
  },
  {
    id: 'lst-104',
    supplierId: 'usr-sup-05',
    supplierCompanyName: 'North Sea Non-Ferrous & Alloy BV',
    supplierContactName: 'Jan De Vries',
    supplierEmail: 'supplier.rotterdammetals@example.com',
    supplierPhone: '+31 10 4928172',
    supplierCountry: 'Netherlands',
    commodityCategory: 'Metal Scrap',
    materialName: 'Copper Wire Scrap (Millberry / Barley)',
    scrapType: 'Non-Ferrous Metal',
    grade: 'ISRI Berry / Barley 99.9% Cu',
    description: 'Clean unalloyed uncoated bright copper wire scrap. Free from brittle burnt wire, insulation residue, and oxidation. Premium remelt grade with minimal dross formation.',
    quantity: 120,
    quantityUnit: 'MT',
    numberOfContainers: 5,
    pricePerUnit: 8750,
    currency: 'USD',
    countryOfOrigin: 'Netherlands',
    loadingLocation: 'Waalhaven Scrap Depots, Rotterdam',
    portOfShipping: 'Port of Rotterdam',
    destinationPort: 'Alexandria Port',
    packaging: 'Bundles strapped with high-tensile steel wire',
    qualitySpecification: 'Min 99.9% Copper purity certified by SGS',
    inspectionAvailable: true,
    minOrderQuantity: 25,
    availabilityDate: '2026-09-01',
    validUntil: '2026-09-25',
    paymentTerms: '20% TT Advance + 80% LC at Sight',
    incoterms: 'CIF',
    photos: [
      'https://images.unsplash.com/photo-1535813547-99c456a41d4a?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=800&q=80',
    ],
    status: 'AVAILABLE',
    adminPublishedPrice: true,
    assignedAgentId: 'usr-agt-01',
    assignedAgentName: 'Khalid Mansoor',
    agentRatePerTon: 75,
    interestedBuyerCount: 3,
    matchedDemandCount: 1,
    createdAt: '2026-08-17T14:00:00Z',
    updatedAt: '2026-08-19T11:00:00Z',
  },
  {
    id: 'lst-105',
    supplierId: 'usr-sup-04',
    supplierCompanyName: 'Saudi Eco Material Processing Co',
    supplierContactName: 'Fahad Al-Otaibi',
    supplierEmail: 'supplier.saudiecocorp@example.com',
    supplierPhone: '+966 13 8920192',
    supplierCountry: 'Saudi Arabia',
    commodityCategory: 'Paper Waste',
    materialName: 'Sorted White Office Paper (SOP)',
    scrapType: 'White Ledger Paper',
    grade: 'ISRI Grade 37 (Sorted Office Paper)',
    description: 'Post-consumer sorted white office paper sheets and printed forms. Free from carbon paper, thermal papers, adhesives, and heavy plastic bindings. Ideal for tissue & bleached pulp production.',
    quantity: 600,
    quantityUnit: 'MT',
    numberOfContainers: 25,
    pricePerUnit: 245,
    currency: 'USD',
    countryOfOrigin: 'Saudi Arabia',
    loadingLocation: 'Dammam 2nd Industrial City',
    portOfShipping: 'King Abdulaziz Port (Dammam)',
    destinationPort: 'Hai Phong Port',
    packaging: 'Hydraulically Compressed Bales (Avg 500-800 kg/bale)',
    qualitySpecification: 'Prohibitives <0.2%, Outthrows <1.5%, Brightness >78',
    inspectionAvailable: true,
    minOrderQuantity: 50,
    availabilityDate: '2026-08-30',
    validUntil: '2026-09-30',
    paymentTerms: '30% TT Advance + 70% against BL copy',
    incoterms: 'FOB',
    photos: [
      'https://images.unsplash.com/photo-1586075010923-2dd4570fb338?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1605600659908-0ef719419d41?auto=format&fit=crop&w=800&q=80',
    ],
    status: 'AVAILABLE',
    adminPublishedPrice: true,
    interestedBuyerCount: 1,
    matchedDemandCount: 1,
    createdAt: '2026-08-16T16:20:00Z',
    updatedAt: '2026-08-18T09:00:00Z',
  },
  {
    id: 'lst-106',
    supplierId: 'usr-sup-01',
    supplierCompanyName: 'Gulf Heavy Smelting & Metal Recovery Ltd',
    supplierContactName: 'Tariq Al-Mansoor',
    supplierEmail: 'supplier.gulfmetal@example.com',
    supplierPhone: '+974 44558899',
    supplierCountry: 'Qatar',
    commodityCategory: 'Metal Scrap',
    materialName: 'Stainless Steel 304 Scrap Solids & Turnings',
    scrapType: 'Stainless Steel Alloy',
    grade: 'AISI 304 / 18-8 Grade',
    description: 'Clean solid cuts of AISI 304 stainless steel plates, pipes, and vessel cutouts. Guaranteed minimum 8% Nickel and 18% Chromium. Low carbon and low molybdenum.',
    quantity: 450,
    quantityUnit: 'MT',
    numberOfContainers: 18,
    pricePerUnit: 1480,
    currency: 'USD',
    countryOfOrigin: 'Qatar',
    loadingLocation: 'Salwa Industrial Area Yard',
    portOfShipping: 'Hamad Port (Doha)',
    destinationPort: 'Nhava Sheva (JNPT Mumbai)',
    packaging: 'Loose in 20ft Dry Cargo Container (Approx 25-28 MT)',
    qualitySpecification: 'Ni >= 8.0%, Cr >= 18.0%, Spark & XRF Certified',
    inspectionAvailable: true,
    minOrderQuantity: 50,
    availabilityDate: '2026-08-26',
    validUntil: '2026-09-20',
    paymentTerms: '100% LC at Sight (Irrevocable & Confirmed)',
    incoterms: 'CFR',
    photos: [
      'https://images.unsplash.com/photo-1504917599217-d4dc5ebe6122?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=800&q=80',
    ],
    status: 'AVAILABLE',
    adminPublishedPrice: true,
    assignedAgentId: 'usr-agt-02',
    assignedAgentName: 'Sanjay Patel',
    agentRatePerTon: 35,
    interestedBuyerCount: 2,
    matchedDemandCount: 1,
    createdAt: '2026-08-17T10:00:00Z',
    updatedAt: '2026-08-19T08:30:00Z',
  },
  {
    id: 'lst-107',
    supplierId: 'usr-sup-03',
    supplierCompanyName: 'Emirates Industrial Ferrous Logistics FZE',
    supplierContactName: 'Rashid Khan',
    supplierEmail: 'supplier.emiratesiron@example.com',
    supplierPhone: '+971 4 8812345',
    supplierCountry: 'United Arab Emirates',
    commodityCategory: 'Metal Scrap',
    materialName: 'Aluminium Extrusion 6063 Scrap (Tabor)',
    scrapType: 'Non-Ferrous Aluminium',
    grade: 'ISRI Tata / Toto (Al 6063)',
    description: 'Clean architectural 6063 profile cuts without thermal break, iron screws, or paint contamination. Excellent melting recovery rate exceeding 93%.',
    quantity: 300,
    quantityUnit: 'MT',
    numberOfContainers: 14,
    pricePerUnit: 2050,
    currency: 'USD',
    countryOfOrigin: 'United Arab Emirates',
    loadingLocation: 'Sharjah Industrial Zone 10',
    portOfShipping: 'Jebel Ali Port (Dubai)',
    destinationPort: 'Mundra Port (Gujarat)',
    packaging: 'Bundles strapped with high-tensile steel wire',
    qualitySpecification: 'Al >= 98.5%, Fe <0.35%, Mg 0.45-0.9%',
    inspectionAvailable: true,
    minOrderQuantity: 25,
    availabilityDate: '2026-09-05',
    validUntil: '2026-10-01',
    paymentTerms: '100% LC at Sight (Irrevocable & Confirmed)',
    incoterms: 'CFR',
    photos: [
      'https://images.unsplash.com/photo-1532601224476-15c79f2f7a51?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1504917599217-d4dc5ebe6122?auto=format&fit=crop&w=800&q=80',
    ],
    status: 'AVAILABLE',
    adminPublishedPrice: true,
    assignedAgentId: 'usr-agt-01',
    assignedAgentName: 'Khalid Mansoor',
    agentRatePerTon: 25,
    interestedBuyerCount: 2,
    matchedDemandCount: 1,
    createdAt: '2026-08-18T13:10:00Z',
    updatedAt: '2026-08-19T15:40:00Z',
  },
  {
    id: 'lst-108',
    supplierId: 'usr-sup-02',
    supplierCompanyName: 'Doha Paper Mills & Pulp Recycling Est',
    supplierContactName: 'Ahmed Bin Salem',
    supplierEmail: 'supplier.doharecycling@example.com',
    supplierPhone: '+974 55112233',
    supplierCountry: 'Qatar',
    commodityCategory: 'Paper Waste',
    materialName: 'Old Newspapers (ONP Grade 8)',
    scrapType: 'Newspaper Bales',
    grade: 'ISRI Grade 8 (ONP Special)',
    description: 'Clean unsoiled newsprint baled tightly. Sourced from over-issue publishers and residential collection. Low moisture, no yellowing, free from plastic polybags.',
    quantity: 400,
    quantityUnit: 'MT',
    numberOfContainers: 18,
    pricePerUnit: 165,
    currency: 'USD',
    countryOfOrigin: 'Qatar',
    loadingLocation: 'Industrial Area Zone 57 Yard',
    portOfShipping: 'Hamad Port (Doha)',
    destinationPort: 'Chattogram Port',
    packaging: 'Hydraulically Compressed Bales (Avg 500-800 kg/bale)',
    qualitySpecification: 'Outthrows <1%, Prohibitives <0.25%, Moisture <10%',
    inspectionAvailable: true,
    minOrderQuantity: 100,
    availabilityDate: '2026-08-25',
    validUntil: '2026-09-15',
    paymentTerms: '30% TT Advance + 70% against BL copy',
    incoterms: 'CIF',
    photos: [
      'https://images.unsplash.com/photo-1586075010923-2dd4570fb338?auto=format&fit=crop&w=800&q=80',
    ],
    status: 'SOLD',
    adminPublishedPrice: true,
    interestedBuyerCount: 1,
    matchedDemandCount: 1,
    createdAt: '2026-08-10T08:00:00Z',
    updatedAt: '2026-08-18T16:00:00Z',
  },
  {
    id: 'lst-109',
    supplierId: 'usr-sup-04',
    supplierCompanyName: 'Saudi Eco Material Processing Co',
    supplierContactName: 'Fahad Al-Otaibi',
    supplierEmail: 'supplier.saudiecocorp@example.com',
    supplierPhone: '+966 13 8920192',
    supplierCountry: 'Saudi Arabia',
    commodityCategory: 'Metal Scrap',
    materialName: 'Cast Iron Scrap Auto Break Drums & Rotors',
    scrapType: 'Cast Iron Scrap',
    grade: 'ISRI 252 (Clean Auto Cast)',
    description: 'Clean cast iron automotive parts, brake drums, rotors and cylinder blocks thoroughly degreased. Heavy wall thickness, free from non-ferrous and dirt.',
    quantity: 900,
    quantityUnit: 'MT',
    numberOfContainers: 36,
    pricePerUnit: 360,
    currency: 'USD',
    countryOfOrigin: 'Saudi Arabia',
    loadingLocation: 'Jubail Industrial Yard',
    portOfShipping: 'King Abdulaziz Port (Dammam)',
    destinationPort: 'Port Qasim (Karachi)',
    packaging: 'Loose in 20ft Dry Cargo Container (Approx 25-28 MT)',
    qualitySpecification: 'Graphitic carbon 3.2-3.6%, Si 1.8-2.2%',
    inspectionAvailable: true,
    minOrderQuantity: 100,
    availabilityDate: '2026-09-02',
    validUntil: '2026-10-02',
    paymentTerms: '100% LC at Sight (Irrevocable & Confirmed)',
    incoterms: 'CFR',
    photos: [
      'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=800&q=80',
    ],
    status: 'AVAILABLE',
    adminPublishedPrice: true,
    assignedAgentId: 'usr-agt-02',
    assignedAgentName: 'Sanjay Patel',
    agentRatePerTon: 15,
    interestedBuyerCount: 1,
    matchedDemandCount: 1,
    createdAt: '2026-08-18T10:45:00Z',
    updatedAt: '2026-08-19T13:00:00Z',
  },
  {
    id: 'lst-110',
    supplierId: 'usr-sup-01',
    supplierCompanyName: 'Gulf Heavy Smelting & Metal Recovery Ltd',
    supplierContactName: 'Tariq Al-Mansoor',
    supplierEmail: 'supplier.gulfmetal@example.com',
    supplierPhone: '+974 44558899',
    supplierCountry: 'Qatar',
    commodityCategory: 'Metal Scrap',
    materialName: 'Used Rails (R50 / R65 Cut to 1.5m Lengths)',
    scrapType: 'Ferrous Rails',
    grade: 'GOST 7173-55 / R50-R65',
    description: 'Cut used steel rails suitable for re-rolling or EAF melting. Cut to standard 1.5 meter containerized lengths. Minimum chemical tensile strength verified.',
    quantity: 3500,
    quantityUnit: 'MT',
    numberOfContainers: 140,
    pricePerUnit: 425,
    currency: 'USD',
    countryOfOrigin: 'Qatar',
    loadingLocation: 'Ras Laffan Logistics Staging',
    portOfShipping: 'Ras Laffan Port',
    destinationPort: 'Mundra Port (Gujarat)',
    packaging: 'Loose in 20ft Dry Cargo Container (Approx 25-28 MT)',
    qualitySpecification: 'C 0.54-0.82%, Mn 0.60-1.05%, Si 0.18-0.40%',
    inspectionAvailable: true,
    minOrderQuantity: 500,
    availabilityDate: '2026-09-10',
    validUntil: '2026-10-15',
    paymentTerms: '100% LC at Sight (Irrevocable & Confirmed)',
    incoterms: 'CFR',
    photos: [
      'https://images.unsplash.com/photo-1504917599217-d4dc5ebe6122?auto=format&fit=crop&w=800&q=80',
    ],
    status: 'AVAILABLE',
    adminPublishedPrice: true,
    assignedAgentId: 'usr-agt-01',
    assignedAgentName: 'Khalid Mansoor',
    agentRatePerTon: 22,
    interestedBuyerCount: 5,
    matchedDemandCount: 2,
    createdAt: '2026-08-12T11:00:00Z',
    updatedAt: '2026-08-19T09:30:00Z',
  },
];

// 10 Realistic Buyer Requirements
export const INITIAL_REQUIREMENTS: BuyerRequirement[] = [
  {
    id: 'req-201',
    buyerId: 'usr-buy-01',
    buyerCompanyName: 'Bharat Steelworks & Foundries Ltd',
    buyerContactName: 'Rajesh Sharma',
    buyerEmail: 'buyer.tatafoundry@example.com',
    buyerPhone: '+91 22 66778899',
    buyerCountry: 'India',
    commodityCategory: 'Metal Scrap',
    materialName: 'HMS 1&2 (80:20) Heavy Melting Steel Scrap',
    grade: 'ISRI 200-206 (Thickness >= 6mm)',
    requiredQuantity: 1000,
    quantityUnit: 'MT',
    targetPricePerUnit: 400,
    currency: 'USD',
    destinationCountry: 'India',
    destinationPort: 'Nhava Sheva (JNPT Mumbai)',
    preferredOrigin: 'Qatar',
    requiredDeliveryDate: '2026-09-15',
    packaging: 'Loose in 20ft Dry Cargo Container (Approx 25-28 MT)',
    qualityRequirements: 'Strictly free from ordnance, gas cylinders, and radioactive matter. SGS / Bureau Veritas Pre-shipment Certificate required.',
    inspectionRequired: true,
    paymentTerms: '100% LC at Sight (Irrevocable & Confirmed)',
    incoterms: 'CFR',
    additionalRequirements: 'Prefer monthly recurring supply contract for 6 months if quality meets foundry standard.',
    status: 'ACTIVE',
    createdAt: '2026-08-16T12:00:00Z',
    updatedAt: '2026-08-18T14:30:00Z',
  },
  {
    id: 'req-202',
    buyerId: 'usr-buy-02',
    buyerCompanyName: 'Chattogram Packaging & Kraft Mills Ltd',
    buyerContactName: 'Kamrul Hassan',
    buyerEmail: 'buyer.bengalpaper@example.com',
    buyerPhone: '+880 31 718291',
    buyerCountry: 'Bangladesh',
    commodityCategory: 'Paper Waste',
    materialName: 'OCC Grade 11 (Old Corrugated Cardboard Bales)',
    grade: 'OCC 11 / ISRI PS-2022',
    requiredQuantity: 800,
    quantityUnit: 'MT',
    targetPricePerUnit: 190,
    currency: 'USD',
    destinationCountry: 'Bangladesh',
    destinationPort: 'Chittagong (Chattogram) Port',
    preferredOrigin: 'Qatar',
    requiredDeliveryDate: '2026-09-20',
    packaging: 'Hydraulically Compressed Bales (Avg 500-800 kg/bale)',
    qualityRequirements: 'Moisture not exceeding 12%, minimal outthrows, no wet damaged bales.',
    inspectionRequired: true,
    paymentTerms: '100% LC at Sight (Irrevocable & Confirmed)',
    incoterms: 'CIF',
    additionalRequirements: 'Shipment in 40ft HC containers preferred.',
    status: 'ACTIVE',
    createdAt: '2026-08-17T09:30:00Z',
    updatedAt: '2026-08-19T11:00:00Z',
  },
  {
    id: 'req-203',
    buyerId: 'usr-buy-03',
    buyerCompanyName: 'Anadolu EAF Steelmaking & Rolling AS',
    buyerContactName: 'Mustafa Demir',
    buyerEmail: 'buyer.anadolusteel@example.com',
    buyerPhone: '+90 232 4419281',
    buyerCountry: 'Turkey',
    commodityCategory: 'Metal Scrap',
    materialName: 'Shredded Steel Scrap 211',
    grade: 'ISRI 211 (Density > 70 lbs/cu ft)',
    requiredQuantity: 2000,
    quantityUnit: 'MT',
    targetPricePerUnit: 420,
    currency: 'USD',
    destinationCountry: 'Turkey',
    destinationPort: 'Aliaga Port (Izmir)',
    preferredOrigin: 'United Arab Emirates',
    requiredDeliveryDate: '2026-09-30',
    packaging: 'Loose in 20ft Dry Cargo Container (Approx 25-28 MT)',
    qualityRequirements: 'EAF Grade high-density shredded steel. Minimal non-ferrous content (<1%).',
    inspectionRequired: true,
    paymentTerms: '100% LC at Sight (Irrevocable & Confirmed)',
    incoterms: 'CFR',
    status: 'ACTIVE',
    createdAt: '2026-08-15T15:00:00Z',
    updatedAt: '2026-08-19T10:00:00Z',
  },
  {
    id: 'req-204',
    buyerId: 'usr-buy-05',
    buyerCompanyName: 'Nile Cables & Non-Ferrous Smelting SAE',
    buyerContactName: 'Ibrahim Mostafa',
    buyerEmail: 'buyer.cairocopper@example.com',
    buyerPhone: '+20 2 2481928',
    buyerCountry: 'Egypt',
    commodityCategory: 'Metal Scrap',
    materialName: 'Copper Wire Scrap (Millberry / Barley)',
    grade: 'ISRI Berry / Barley 99.9% Cu',
    requiredQuantity: 100,
    quantityUnit: 'MT',
    targetPricePerUnit: 8800,
    currency: 'USD',
    destinationCountry: 'Egypt',
    destinationPort: 'Alexandria Port',
    preferredOrigin: 'Netherlands',
    requiredDeliveryDate: '2026-09-25',
    packaging: 'Bundles strapped with high-tensile steel wire',
    qualityRequirements: '99.9% Copper purity certificate from internationally accredited lab.',
    inspectionRequired: true,
    paymentTerms: '20% TT Advance + 80% LC at Sight',
    incoterms: 'CIF',
    status: 'ACTIVE',
    createdAt: '2026-08-18T14:15:00Z',
    updatedAt: '2026-08-19T13:45:00Z',
  },
  {
    id: 'req-205',
    buyerId: 'usr-buy-04',
    buyerCompanyName: 'Saigon Containerboard & Duplex Packaging Corp',
    buyerContactName: 'Nguyen Van Minh',
    buyerEmail: 'buyer.saigonboard@example.com',
    buyerPhone: '+84 28 3829102',
    buyerCountry: 'Vietnam',
    commodityCategory: 'Paper Waste',
    materialName: 'Sorted White Office Paper (SOP)',
    grade: 'ISRI Grade 37 (Sorted Office Paper)',
    requiredQuantity: 500,
    quantityUnit: 'MT',
    targetPricePerUnit: 250,
    currency: 'USD',
    destinationCountry: 'Vietnam',
    destinationPort: 'Hai Phong Port',
    preferredOrigin: 'Saudi Arabia',
    requiredDeliveryDate: '2026-10-05',
    packaging: 'Hydraulically Compressed Bales (Avg 500-800 kg/bale)',
    qualityRequirements: 'Clean unsoiled paper, no plastic wraps or heavy ink bleed.',
    inspectionRequired: true,
    paymentTerms: '30% TT Advance + 70% against BL copy',
    incoterms: 'CFR',
    status: 'ACTIVE',
    createdAt: '2026-08-17T11:00:00Z',
    updatedAt: '2026-08-18T16:20:00Z',
  },
];

// Initial Transactions
export const INITIAL_TRANSACTIONS: Transaction[] = [
  {
    id: 'txn-501',
    dealCode: 'AST-2026-081',
    listingId: 'lst-101',
    requirementId: 'req-201',
    supplierId: 'usr-sup-01',
    supplierName: 'Gulf Heavy Smelting & Metal Recovery Ltd',
    buyerId: 'usr-buy-01',
    buyerName: 'Bharat Steelworks & Foundries Ltd',
    agentId: 'usr-agt-01',
    agentName: 'Khalid Mansoor',
    materialName: 'HMS 1&2 (80:20) Heavy Melting Steel Scrap',
    commodity: 'Metal Scrap',
    grade: 'ISRI 200-206',
    quantity: 1000,
    unit: 'MT',
    purchasePricePerUnit: 375,
    sellingPricePerUnit: 405,
    currency: 'USD',
    totalPurchaseValue: 375000,
    totalSalesValue: 405000,
    freightAndLogisticsCost: 12000,
    inspectionAndInsuranceCost: 3500,
    agentCommissionPerTon: 15,
    totalAgentCommission: 15000, // 1000 MT * $15/MT
    grossMargin: 14500, // 405,000 - 375,000 - 12,000 - 3,500 = 14,500
    netMargin: 14500,
    status: 'IN_PROGRESS',
    type: 'AGENT_TRADING',
    originPort: 'Hamad Port (Doha)',
    destinationPort: 'Nhava Sheva (JNPT Mumbai)',
    incoterms: 'CFR',
    paymentStatus: 'LC_OPENED',
    shipmentStatus: 'CONTAINER_LOADED',
    contractNumber: 'AST/CONT/2026/081-QA-IN',
    createdAt: '2026-08-17T10:00:00Z',
    updatedAt: '2026-08-19T12:00:00Z',
  },
  {
    id: 'txn-502',
    dealCode: 'AST-2026-079',
    listingId: 'lst-108',
    supplierId: 'usr-sup-02',
    supplierName: 'Doha Paper Mills & Pulp Recycling Est',
    buyerId: 'usr-buy-02',
    buyerName: 'Chattogram Packaging & Kraft Mills Ltd',
    materialName: 'Old Newspapers (ONP Grade 8)',
    commodity: 'Paper Waste',
    grade: 'ISRI Grade 8 (ONP Special)',
    quantity: 400,
    unit: 'MT',
    purchasePricePerUnit: 150,
    sellingPricePerUnit: 172,
    currency: 'USD',
    totalPurchaseValue: 60000,
    totalSalesValue: 68800,
    freightAndLogisticsCost: 4200,
    inspectionAndInsuranceCost: 1100,
    agentCommissionPerTon: 0,
    totalAgentCommission: 0,
    grossMargin: 3500,
    netMargin: 3500,
    status: 'COMPLETED',
    type: 'DIRECT_TRADING',
    originPort: 'Hamad Port (Doha)',
    destinationPort: 'Chattogram Port',
    incoterms: 'CIF',
    paymentStatus: 'FULLY_SETTLED',
    shipmentStatus: 'CLEARED',
    contractNumber: 'AST/CONT/2026/079-QA-BD',
    createdAt: '2026-08-10T09:00:00Z',
    updatedAt: '2026-08-18T16:00:00Z',
  },
];

// Initial Agent Assignments
export const INITIAL_AGENT_ASSIGNMENTS: AgentAssignment[] = [
  {
    id: 'asg-301',
    listingId: 'lst-101',
    agentId: 'usr-agt-01',
    agentName: 'Khalid Mansoor',
    agentEmail: 'agent.khalid@example.com',
    materialName: 'HMS 1&2 (80:20) Heavy Melting Steel Scrap',
    commodity: 'Metal Scrap',
    quantityMT: 1000,
    agentRatePerTon: 18,
    calculatedAgentAmount: 18000, // 1000 * 18
    commercialTerms: 'CFR Nhava Sheva or Mundra. Minimum target price $405/MT. LC at Sight.',
    targetSalesPrice: 405,
    currency: 'USD',
    status: 'IN_NEGOTIATION',
    latestUpdate: 'Presented specifications to top two Indian foundry buyers; awaiting official PO draft.',
    assignedAt: '2026-08-16T10:00:00Z',
    updatedAt: '2026-08-19T14:30:00Z',
  },
  {
    id: 'asg-302',
    listingId: 'lst-103',
    agentId: 'usr-agt-03',
    agentName: 'Selim Erdogan',
    agentEmail: 'agent.selim@example.com',
    materialName: 'Shredded Steel Scrap 211',
    commodity: 'Metal Scrap',
    quantityMT: 2200,
    agentRatePerTon: 20,
    calculatedAgentAmount: 44000, // 2200 * 20
    commercialTerms: 'CFR Aliaga Port / Iskenderun. Target price $420/MT. Irrevocable Confirmed LC.',
    targetSalesPrice: 420,
    currency: 'USD',
    status: 'ASSIGNED',
    latestUpdate: 'Reviewing mill capacity in Izmir industrial belt.',
    assignedAt: '2026-08-18T11:00:00Z',
    updatedAt: '2026-08-19T09:00:00Z',
  },
  {
    id: 'asg-303',
    listingId: 'lst-102',
    agentId: 'usr-agt-02',
    agentName: 'Sanjay Patel',
    agentEmail: 'agent.sanjay@example.com',
    materialName: 'OCC Grade 11 (Old Corrugated Cardboard Bales)',
    commodity: 'Paper Waste',
    quantityMT: 850,
    agentRatePerTon: 12,
    calculatedAgentAmount: 10200, // 850 * 12
    commercialTerms: 'CIF Chittagong Port. Target price $190/MT.',
    targetSalesPrice: 190,
    currency: 'USD',
    status: 'BUYER_IDENTIFIED',
    latestUpdate: 'Buyer expressed interest for 800 MT; verifying LC confirmation terms.',
    assignedAt: '2026-08-17T15:00:00Z',
    updatedAt: '2026-08-19T16:15:00Z',
  },
];

// Initial Documents
export const INITIAL_DOCUMENTS: TradeDocument[] = [
  {
    id: 'doc-601',
    transactionId: 'txn-501',
    listingId: 'lst-101',
    title: 'Pre-Shipment Inspection & Radioactivity Certificate',
    documentType: 'INSPECTION_REPORT',
    fileName: 'SGS_Inspection_HMS_AST-081.pdf',
    fileSize: '2.4 MB',
    fileUrl: '#',
    uploadedBy: 'Admin (Al Shaheed Trading)',
    accessRoles: ['ADMIN', 'BUYER', 'SUPPLIER'],
    uploadedAt: '2026-08-18T14:00:00Z',
    status: 'VERIFIED',
  },
  {
    id: 'doc-602',
    transactionId: 'txn-501',
    listingId: 'lst-101',
    title: 'Commercial Invoice & Weight Certificate',
    documentType: 'COMMERCIAL_INVOICE',
    fileName: 'AlShaheed_Invoice_AST-2026-081.pdf',
    fileSize: '1.8 MB',
    fileUrl: '#',
    uploadedBy: 'Admin (Al Shaheed Trading)',
    accessRoles: ['ADMIN', 'BUYER'],
    uploadedAt: '2026-08-19T09:30:00Z',
    status: 'VERIFIED',
  },
];

// Initial Notifications
export const INITIAL_NOTIFICATIONS: Notification[] = [
  {
    id: 'notif-001',
    recipientId: 'ADMIN_ALL',
    recipientRole: 'ADMIN',
    title: 'High-Score Supply-Demand Match Identified',
    message: 'System matched HMS 1&2 (1,500 MT) from Qatar with Bharat Steelworks requirement (1,000 MT). Match score: 96%.',
    type: 'MATCH',
    linkUrl: '/admin/matching',
    isRead: false,
    priority: 'HIGH',
    createdAt: '2026-08-19T14:30:00Z',
  },
  {
    id: 'notif-002',
    recipientId: 'ADMIN_ALL',
    recipientRole: 'ADMIN',
    title: 'Buyer Interest Expressed',
    message: 'Anadolu EAF Steelmaking expressed interest in Shredded Steel Scrap 211 — 2,000 MT.',
    type: 'DEAL',
    linkUrl: '/admin/marketplace',
    isRead: false,
    priority: 'HIGH',
    createdAt: '2026-08-19T12:15:00Z',
  },
  {
    id: 'notif-003',
    recipientId: 'usr-agt-01',
    recipientRole: 'AGENT',
    title: 'New Material Assigned by Admin',
    message: 'You have been assigned HMS 1&2 Scrap (1,000 MT). Agent Rate: $18.00/MT (Expected compensation: $18,000).',
    type: 'INFO',
    linkUrl: '/agent/assigned',
    isRead: false,
    priority: 'HIGH',
    createdAt: '2026-08-16T10:00:00Z',
  },
  {
    id: 'notif-004',
    recipientId: 'usr-sup-01',
    recipientRole: 'SUPPLIER',
    title: 'Listing Approved on Trading Platform',
    message: 'Your listing "HMS 1&2 (80:20) Heavy Melting Steel Scrap" has been verified and approved for the marketplace.',
    type: 'SUCCESS',
    linkUrl: '/supplier/listings',
    isRead: true,
    priority: 'NORMAL',
    createdAt: '2026-08-15T10:00:00Z',
  },
];

// Initial Audit Logs
export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'log-001',
    userId: 'usr-admin-01',
    userName: 'Mohamed Shiham',
    userRole: 'ADMIN',
    action: 'MATCH_PROCESSED',
    entity: 'MatchResult',
    entityId: 'lst-101 <-> req-201',
    previousValue: 'NEW (96% Score)',
    newValue: 'DEAL_INITIATED',
    ipAddress: '192.168.1.10',
    timestamp: '2026-08-19T14:35:00Z',
  },
  {
    id: 'log-002',
    userId: 'usr-admin-01',
    userName: 'Mohamed Shiham',
    userRole: 'ADMIN',
    action: 'AGENT_ASSIGNMENT_CREATED',
    entity: 'AgentAssignment',
    entityId: 'asg-301',
    previousValue: 'None',
    newValue: 'Assigned Khalid Mansoor @ $18/MT for 1000 MT ($18,000 total)',
    ipAddress: '192.168.1.10',
    timestamp: '2026-08-16T10:05:00Z',
  },
  {
    id: 'log-003',
    userId: 'usr-sup-01',
    userName: 'Tariq Al-Mansoor',
    userRole: 'SUPPLIER',
    action: 'LISTING_SUBMITTED',
    entity: 'ScrapListing',
    entityId: 'lst-101',
    previousValue: 'Draft',
    newValue: '1500 MT HMS 1&2 @ $395/MT',
    ipAddress: '89.211.45.12',
    timestamp: '2026-08-15T09:00:00Z',
  },
];
